-- ==============================================================================
-- GUIANZAPP - SCRIPT DE MIGRACIÓN SQL PARA SUPABASE
-- Sistema de Especialidades por Categorías, Separación de Perfil de Guías,
-- Programación de Salidas con Cupos por Horario y Matching con Agencias
-- ==============================================================================

-- IMPORTANTE SOBRE EL USUARIO ADMINISTRADOR:
-- La tabla `perfiles` existente se mantiene INTACTA para el usuario Administrador y Agencias.
-- El usuario Administrador sigue residiendo en `perfiles` con `rol = 'administrador'`,
-- por lo que sus credenciales, permisos y flujo de aprobación/rechazo NO sufren alteración.
-- La nueva tabla `perfil_guias` se enlaza mediante `usuario_id` a `auth.users(id)`
-- y se sincroniza automáticamente con el panel de administración.

-- ==============================================================================
-- 1. TABLA: especialidades (Catálogo Maestro Global)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.especialidades (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_macro VARCHAR(100) NOT NULL,
    subcategoria VARCHAR(150) NOT NULL,
    descripcion_ayuda TEXT NULL,
    icono VARCHAR(10) NULL,
    creado_en TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_especialidad_subcategoria UNIQUE (categoria_macro, subcategoria)
);

-- ==============================================================================
-- 2. POBLAR TABLA especialidades (Seed Data - 4 Categorías, 19 Subcategorías)
-- ==============================================================================
INSERT INTO public.especialidades (categoria_macro, subcategoria, descripcion_ayuda, icono)
VALUES 
    -- Categoría 1: Historia, Patrimonio y Cultura Urbana 🏛️
    ('Historia, Patrimonio y Cultura Urbana', 
     'Centros Históricos y Localidades (La Candelaria, Teusaquillo, Usaquén)', 
     'Rutas por callejones coloniales, arquitectura patrimonial y narración de la fundación de la ciudad.', '🏛️'),
    ('Historia, Patrimonio y Cultura Urbana', 
     'Arquitectura y Monumentos (Colonial, Barroco, Republicano, Moderno)', 
     'Recorridos arquitectónicos de épocas virreinal, republicana, modernista e internacional.', '🏛️'),
    ('Historia, Patrimonio y Cultura Urbana', 
     'Historia, Antropología y Arqueología (Museos, Mitos, Precolombino)', 
     'Visitas especializadas en Museo del Oro, Museo Nacional, Botero, MAMU y cosmogonía indígena.', '🏛️'),
    ('Historia, Patrimonio y Cultura Urbana', 
     'Arte Urbano, Graffiti y Contracultura', 
     'Distrito Graffiti, Calle 26, Chapinero, muralismo con contenido social y técnicas de stencil.', '🏛️'),
    ('Historia, Patrimonio y Cultura Urbana', 
     'Turismo Religioso y Miradores (Monserrate, Guadalupe, Iglesias)', 
     'Santuarios de altura, miradores panorámicos del altiplano e iglesias virreinales del centro.', '🏛️'),

    -- Categoría 2: Gastronomía, Estilo de Vida y Entretenimiento ☕
    ('Gastronomía, Estilo de Vida y Entretenimiento', 
     'Cafés de Especialidad y Catas de Barismo', 
     'Rutas de cafés de origen, perfiles de taza, métodos de filtrado y barismo en Quinta Camacho y Chapinero.', '☕'),
    ('Gastronomía, Estilo de Vida y Entretenimiento', 
     'Plazas de Mercado, Frutas Tropicales y Comida Tradicional', 
     'Degustación sensorial de frutas exóticas, ajiaco, lechona y arepas en Paloquemao, La Perseverancia o Restrepo.', '☕'),
    ('Gastronomía, Estilo de Vida y Entretenimiento', 
     'Alta Cocina, Zonas Gourmet y Rutas Gastronómicas', 
     'Experiencias en Zona G, Zona T, Usaquén, restaurantes de autor y cocina colombiana contemporánea.', '☕'),
    ('Gastronomía, Estilo de Vida y Entretenimiento', 
     'Vida Nocturna, Rumba, Bares de Salsa, Cerveza Artesanal y Tejo', 
     'Clubes tradicionales de tejo (deporte nacional), rumba nocturna, salsa y microcervecerías locales.', '☕'),
    ('Gastronomía, Estilo de Vida y Entretenimiento', 
     'Compras, Mercados de Pulgas y Artesanías', 
     'Mercado de Pulgas de Usaquén y San Alejo, diseño de autor, pasajes de esmeraldas y artesanías.', '☕'),

    -- Categoría 3: Naturaleza, Biodiversidad y Aventura 🥾
    ('Naturaleza, Biodiversidad y Aventura', 
     'Senderismo y Montañismo (Cerros Orientales, Páramos, Chicaque)', 
     'Trekking en Quebrada La Vieja, Páramo de Chingaza, Cruz Verde, Matarredonda, La Chorrera y Chicaque.', '🥾'),
    ('Naturaleza, Biodiversidad y Aventura', 
     'Avistamiento de Aves y Reconocimiento de Humedales', 
     'Birdwatching en humedales La Conejera, Santa María del Lago, Tibanica y observatorios de colibríes.', '🥾'),
    ('Naturaleza, Biodiversidad y Aventura', 
     'Turismo de Aventura, Escalada, Ciclomontañismo y Espeleología', 
     'Escalada en roca en Suesca, espeleología en cavernas y descensos técnicos en bicicleta.', '🥾'),
    ('Naturaleza, Biodiversidad y Aventura', 
     'Biciturismo Urbano y Ciclovía dominical', 
     'Circuitos guiados en bicicleta por la red de ciclorrutas de Bogotá y la tradicional Ciclovía dominical.', '🥾'),
    ('Naturaleza, Biodiversidad y Aventura', 
     'Bienestar, Conexión Natural, Termales y Baños de Bosque', 
     'Shinrin-yoku (baños de bosque), meditación, retiros holísticos y termales en la cordillera.', '🥾'),

    -- Categoría 4: Turismo Comunitario, Social y Rural 🌍
    ('Turismo Comunitario, Social y Rural', 
     'Transformación Social y Muralismo Comunitario (Ciudad Bolívar, San Cristóbal)', 
     'Ascenso en TransMiCable a El Paraíso, relatos de memoria comunitaria y liderazgos locales de barrio.', '🌍'),
    ('Turismo Comunitario, Social y Rural', 
     'Turismo de Memoria, Paz y Reconciliación', 
     'Visitas al Centro de Memoria, Paz y Reconciliación, monumento Fragmentos y pedagogía de paz.', '🌍'),
    ('Turismo Comunitario, Social y Rural', 
     'Cultura Campesina, Ruralidad y Huertas Urbanas (Usme, Sumapaz)', 
     'Ruta de la fresa en Usme Rural, necrópolis indígena, agroecología y páramo de Sumapaz.', '🌍'),
    ('Turismo Comunitario, Social y Rural', 
     'Etnografía, Saberes Ancestrales y Medicina Tradicional', 
     'Encuentros interculturales con pueblos originarios asentados en Bogotá, tejidos y saberes medicinales.', '🌍')
ON CONFLICT (categoria_macro, subcategoria) DO UPDATE 
SET descripcion_ayuda = EXCLUDED.descripcion_ayuda,
    icono = EXCLUDED.icono;

-- ==============================================================================
-- 3. TABLA: perfil_guias (Especializada para Guías de Turismo)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.perfil_guias (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre_completo VARCHAR(150) NOT NULL,
    tarjeta_profesional VARCHAR(50) NOT NULL UNIQUE,
    telefono_principal VARCHAR(20) NOT NULL,
    tiene_whatsapp BOOLEAN DEFAULT TRUE,
    telefono_alternativo VARCHAR(20) NULL,
    contacto_emergencia_nombre VARCHAR(100) NOT NULL,
    contacto_emergencia_tel VARCHAR(20) NOT NULL,
    reseña_corta VARCHAR(300) NOT NULL,
    experiencia_detalle TEXT NOT NULL,
    competencias_tec TEXT NULL,
    idiomas VARCHAR(200) NOT NULL DEFAULT 'Español',
    url_foto_rostro TEXT NULL,
    url_rnt TEXT NULL,
    url_tarjeta_profesional TEXT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente', -- 'pendiente', 'activo', 'rechazado'
    motivo_rechazo TEXT NULL,
    creado_en TIMESTAMPTZ DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 4. TABLA: guia_especialidades (Tabla Pivote / Relación Muchos a Muchos)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.guia_especialidades (
    guia_id INT NOT NULL REFERENCES public.perfil_guias(id) ON DELETE CASCADE,
    especialidad_id INT NOT NULL REFERENCES public.especialidades(id) ON DELETE CASCADE,
    asignado_en TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (guia_id, especialidad_id)
);

-- ==============================================================================
-- 5. TABLA: paquetes_tours (Productos Turísticos Creados por Agencias)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.paquetes_tours (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre_tour VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    duracion_horas INT NOT NULL,
    precio NUMERIC(12,2) NOT NULL DEFAULT 0,
    cupos_totales INT NOT NULL DEFAULT 15,
    ubicacion VARCHAR(150) NOT NULL DEFAULT 'Bogotá D.C.',
    nivel_dificultad VARCHAR(50) NOT NULL DEFAULT 'Baja',
    punto_encuentro TEXT NULL,
    que_incluye TEXT NULL,
    recomendaciones TEXT NULL,
    imagenes TEXT[] DEFAULT '{}',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 6. TABLA: tour_especialidades (Pivote para el Matching con Perfiles de Guía)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.tour_especialidades (
    tour_id INT NOT NULL REFERENCES public.paquetes_tours(id) ON DELETE CASCADE,
    especialidad_id INT NOT NULL REFERENCES public.especialidades(id) ON DELETE CASCADE,
    agregado_en TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (tour_id, especialidad_id)
);

-- ==============================================================================
-- 7. TABLA: programacion_tours (Salidas y Horarios con Control de Cupos)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.programacion_tours (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id INT NOT NULL REFERENCES public.paquetes_tours(id) ON DELETE CASCADE,
    guia_id INT NULL REFERENCES public.perfil_guias(id) ON DELETE SET NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    cupos_maximos INT NOT NULL,
    cupos_disponibles INT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Disponible', -- 'Disponible', 'Completo', 'Cancelado'
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para optimizar consultas de reservas y matching
CREATE INDEX IF NOT EXISTS idx_programacion_tour_fecha ON public.programacion_tours (tour_id, fecha, estado);
CREATE INDEX IF NOT EXISTS idx_guia_especialidades_guia ON public.guia_especialidades (guia_id);
CREATE INDEX IF NOT EXISTS idx_tour_especialidades_tour ON public.tour_especialidades (tour_id);

-- ==============================================================================
-- 8. MIGRACIÓN DE DATOS PREEXISTENTES (Si ya existen guías en la tabla `perfiles`)
-- ==============================================================================
-- Copia a los guías que ya estaban registrados en `perfiles` hacia `perfil_guias`
INSERT INTO public.perfil_guias (
    usuario_id,
    nombre_completo,
    tarjeta_profesional,
    telefono_principal,
    tiene_whatsapp,
    telefono_alternativo,
    contacto_emergencia_nombre,
    contacto_emergencia_tel,
    reseña_corta,
    experiencia_detalle,
    competencias_tec,
    idiomas,
    estado
)
SELECT 
    p.id AS usuario_id,
    COALESCE(p.nombre_completo, 'Guía Profesional') AS nombre_completo,
    COALESCE(p.numero_rnt, 'RNT-' || SUBSTRING(p.id::text, 1, 6)) AS tarjeta_profesional,
    '+573000000000' AS telefono_principal,
    TRUE AS tiene_whatsapp,
    NULL AS telefono_alternativo,
    'Contacto de Emergencia' AS contacto_emergencia_nombre,
    '+573000000000' AS contacto_emergencia_tel,
    'Guía profesional de turismo certificado para recorridos en Bogotá.' AS reseña_corta,
    'Experiencia guiando turistas nacionales e internacionales en Bogotá.' AS experiencia_detalle,
    'Primeros auxilios básicos' AS competencias_tec,
    COALESCE(p.idiomas, 'Español') AS idiomas,
    COALESCE(p.estado::text, 'aprobado') AS estado
FROM public.perfiles p
WHERE p.rol = 'guia'
ON CONFLICT (usuario_id) DO NOTHING;

-- Copia paquetes turísticos antiguos a `paquetes_tours` si existe la tabla `paquetes`
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'paquetes') THEN
        INSERT INTO public.paquetes_tours (
            agencia_id,
            nombre_tour,
            descripcion,
            duracion_horas,
            precio,
            cupos_totales,
            ubicacion,
            nivel_dificultad,
            punto_encuentro,
            que_incluye,
            recomendaciones,
            imagenes,
            activo
        )
        SELECT 
            p.agencia_id,
            p.nombre AS nombre_tour,
            p.descripcion,
            COALESCE(p.duracion_horas, 4) AS duracion_horas,
            COALESCE(p.precio, 0) AS precio,
            COALESCE(p.cupos_maximos, p.cupos_totales, 15) AS cupos_totales,
            COALESCE(p.ubicacion, 'Bogotá D.C.') AS ubicacion,
            COALESCE(p.nivel_dificultad, 'Baja') AS nivel_dificultad,
            p.punto_encuentro,
            p.incluye AS que_incluye,
            p.recomendaciones,
            COALESCE(p.imagenes, '{}'),
            COALESCE(p.activo, TRUE)
        FROM public.paquetes p
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- ==============================================================================
-- 9. POLÍTICAS DE ACCESO (ROW LEVEL SECURITY - RLS)
-- ==============================================================================
ALTER TABLE public.especialidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil_guias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guia_especialidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paquetes_tours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tour_especialidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programacion_tours ENABLE ROW LEVEL SECURITY;

-- especialidades: lectura pública para todos los usuarios
CREATE POLICY "Especialidades lectura pública" 
ON public.especialidades FOR SELECT USING (true);

-- perfil_guias: lectura pública para guías aprobados, edición propia o de admin
CREATE POLICY "Perfil guías lectura pública de aprobados" 
ON public.perfil_guias FOR SELECT USING (estado::text = 'aprobado' OR auth.uid() = usuario_id);

CREATE POLICY "Guía edita su propio perfil" 
ON public.perfil_guias FOR UPDATE USING (auth.uid() = usuario_id);

CREATE POLICY "Guía inserta su propio perfil" 
ON public.perfil_guias FOR INSERT WITH CHECK (auth.uid() = usuario_id);

-- guia_especialidades: lectura pública, modificación por el guía
CREATE POLICY "Guía especialidades lectura pública" 
ON public.guia_especialidades FOR SELECT USING (true);

-- paquetes_tours: lectura pública de activos, gestión por agencia creadora
CREATE POLICY "Paquetes lectura pública de activos" 
ON public.paquetes_tours FOR SELECT USING (activo = true OR auth.uid() = agencia_id);

CREATE POLICY "Agencia gestiona sus propios paquetes" 
ON public.paquetes_tours FOR ALL USING (auth.uid() = agencia_id);

-- tour_especialidades y programacion_tours: lectura pública
CREATE POLICY "Tour especialidades lectura pública" 
ON public.tour_especialidades FOR SELECT USING (true);

CREATE POLICY "Programación tours lectura pública" 
ON public.programacion_tours FOR SELECT USING (true);

-- ==============================================================================
-- FIN DEL SCRIPT DE MIGRACIÓN
-- ==============================================================================
